### ISSUE TITLE
DAP for a custom language

### ISSUE THREAD

**Issue by ankkumar-progress** [eclipse/lsp4j#312] opened 2019-03-31 19:19 UTC
We are trying to write a DAP for [ABL](https://en.wikipedia.org/wiki/OpenEdge_Advanced_Business_Language) language using java.
I was hoping if you guys can provide some sample (Hello world ) for DAP.
I was going through the [readme](https://github.com/eclipse/lsp4j) file, but it seems it is mainly for LSP.
Can you point me to some correct source to start with?

**Comment by ankkumar-progress** [comment] 2019-04-07 10:29
The documentation [link](https://github.com/eclipse/lsp4j/blob/master/documentation/README.md) that you have in your repo is for LSP. Correct me If I am wrong.

Do you have any link for DAP documentation to consume the lsp4j sdk ?

**Comment by spoenemann** [comment] 2019-04-08 06:57
Yes, the examples in the documentation are for LSP, but it should work very similarly for DAP. There's a class `DSPLauncher` for that.

Closing since this is somewhat a duplicate of #258.

**Closed by spoenemann** 2019-04-08 06:57 UTC
