### ISSUE TITLE
NumberFormatException with latest LSP4J

### ISSUE THREAD

**Issue by PyvesB** [eclipse/lsp4j#415] opened 2020-02-27 16:07 UTC
Hello there,

I tried running my [Ruby DAP plugin](https://github.com/PyvesB/eclipse-solargraph) with the latest version of LSP4J, and it no longer works. I'm getting the following stack trace:
```
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 70268739693720 at line 1 column 90 path $.body.threadId
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:227)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:217)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.fromJson(MessageTypeAdapter.java:329)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.parseParams(MessageTypeAdapter.java:249)
	at org.eclipse.lsp4j.jsonrpc.debug.adapters.DebugMessageTypeAdapter.parseBody(DebugMessageTypeAdapter.java:294)
	at org.eclipse.lsp4j.jsonrpc.debug.adapters.DebugMessageTypeAdapter.read(DebugMessageTypeAdapter.java:243)
	at org.eclipse.lsp4j.jsonrpc.debug.adapters.DebugMessageTypeAdapter.read(DebugMessageTypeAdapter.java:157)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:119)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: Expected an int but was 70268739693720 at line 1 column 90 path $.body.threadId
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1172)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:225)
	... 20 more
```

The faulty debugger response is the following:
```
{"type":"response","request_seq":6,"success":true,"command":"threads","body":{"threads":[{"id":70268739693720,"name":"Thread 1"}]}}
```

The [specification](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Thread) states that the thread ID should be of type number, but I'm unsure what that means exactly. Isn't 70268739693720 a valid number?

Thanks in advance for clarifying!

**Comment by cdietrich** [comment] 2020-02-27 16:09
70268739693720 Might be > integer.maxvalue

**Comment by PyvesB** [comment] 2020-02-27 16:10
> 70268739693720 Might be > integer.maxvalue

It is. However, is this forbidden by the DAP specification?

**Comment by jonahgraham** [comment] 2020-02-27 16:10
It **must** be 32-bit. I will cite references momentarily.

**Comment by jonahgraham** [comment] 2020-02-27 16:18
We fixed this in #392 and documented it as a breaking change for 0.9.0: https://github.com/eclipse/lsp4j/blob/master/CHANGELOG.md#v090-feb-2020 which is essentially driven by spec change https://github.com/microsoft/debug-adapter-protocol/pull/63

Note that some adapters in the past have used 64-bit values  (namely https://github.com/microsoft/vscode-python/pull/761) but this didn't work with VScode as javascript uses a number format that can't store 64-bit integers properly :-)

**Comment by PyvesB** [comment] 2020-02-27 17:08
Hmmm... I'm only half convinced. 😄 

The specification indicates `The value should be less than or equal to 2147483647 (2^31 - 1)` for a lot of these values, but not this particular thread id one (see description here: https://github.com/microsoft/debug-adapter-protocol/blob/ccf658360d5ce9bdc7b46a7ff0f4b71ca21fbe5b/debugAdapterProtocol.json#L2757). Nothing in the spec clearly defines what `integer` is as far as I can tell. @jonahgraham you requested clarification yourself [here](https://github.com/microsoft/debug-adapter-protocol/issues/90#issuecomment-578865031), but there has not yet been a response.

Just because VS Code's Javascript implementation of the specification doesn't support anything above 32 bits shouldn't necessarily force LSP4J's implementation to constrain itself as well, especially as the specification is not unambiguously backing those constraints.

Also, worth noting that in VSCode Python's example, the value simply overflowed and only caused an issue in a particular edge-case involving Live Share, whereas in the case of LSP4J the `Threads` messages can no longer be parsed and systematically cause the whole debug session to fall over.

**Comment by jonahgraham** [comment] 2020-02-27 17:39
There are two issues being mixed here.

1) LSP4J's JSON-RPC implementation that "falls over" if the data on the wire violates the expectation in the Java code.
2) The size of these particular fields.

For 2. I have pinged https://github.com/microsoft/debug-adapter-protocol/issues/90 for confirmation. But based on the track record here this will all but certainly be confirmed. 

As for 1. this is a design decision in LSP4J - it does cause problems and sometimes causes things to fallover in bad places when servers and clients are not 100% compatible. I think this is the client's responsibility to handle and report these errors to the user that there is some compatibility error.  LSP4J could make this easier by not passing internal exceptions (like JsonSyntaxException) to client/servers.

Presumably the ruby debug server you are providing uses some internal ID? Does it have a range bigger than 32-bit but less than 64-bit? e.g. Do you constrain it to be < 52-bits?

**Comment by jonahgraham** [comment] 2020-02-27 17:50
I see the debug adapter is provided by https://github.com/castwide/readapt? AFAICT https://github.com/castwide/readapt/blob/b890d5026bb058cebcd3aa6fa29b99faa498876a/ext/readapt/monitor.c#L55 has the same issue that the older python adapter had of using the internal 64-bit [object_id](https://apidock.com/ruby/Object/object_id) as the thread_id. This won't work in VSCode, VS and now LSP4J/E. However it will fallover in different ways. In VSCode/VS it will work unless the the thread happens to be allocated to an address that can't be stored in a double in a recoverable way. So some users will probably randomly have individual threads the don't work as expected.

**Comment by jonahgraham** [comment] 2020-02-27 17:50
https://github.com/castwide/readapt/blob/e082694c36c839a6d2bb973d004ddf5e987002f3/ext/readapt/threads.c#L40 would be a better link to the extraction from ruby.

**Comment by jonahgraham** [comment] 2020-02-27 19:14
Hi @PyvesB,

We were supposed to release the 0.9.0 release of LSP4J today. I very much appreciate that you have taken time to test against a pre-release and identified a problem that may need resolving.
I want to know if you have a suggestion about what to do here - i.e. do you think that you can work to get the ruby DAP fixed between now and SimRel release time of March 18th?

I'm going to reopen this for now because I really don't like the idea of breaking consumers of the API that are active and want to work to find a solution. The solution may be to handle the JSON exception better either here, or in LSP4E, so that users of the Ruby DAP have some indication that they need to upgrade. 

Thanks and WDYT?
Jonah

**Comment by PyvesB** [comment] 2020-02-27 19:44
Thanks for pinging on https://github.com/microsoft/debug-adapter-protocol/issues/90 @jonahgraham! Hopefully this will result in a clearer specification for everyone. 👍 

My current thinking is the following: don't let the Ruby integration block the release of LSP4J. Ruby support in Eclipse has historically not been used by that many developers, debugging in that language is even more of a niche feature. It's not worth us making too much of a fuss about it.

I'll raise an issue with Readapt and attempt a pull request myself. As long as the fix to Readapt gets released in the coming weeks, all will be fine. Ideally, I would have liked to be able to point to an unambiguous section of the specification stating "this **_must_** be a 32-bit integer", but hopefully the fix will be accepted without that!

**Comment by jonahgraham** [comment] 2020-02-27 20:54
thanks for the quick response. I'll proceed with 0.9.0 release.

**Closed by jonahgraham** 2020-02-27 20:54 UTC
