### ISSUE TITLE
LSP initialize message definition is not compliant with 3.16 spec

### ISSUE THREAD

**Issue by pablocabrera85** [eclipse/lsp4j#478] opened 2020-12-17 12:21 UTC
When trying to connect to a language server from custom vscode extension using v0.10.0, a serialization exception is thrown because the field **prepareSupportDefaultBehavior** at **org.eclipse.lsp4j.RenameCapabilities** was modelled as a boolean, but the spec specified it is constant Identifier (see [here](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_rename)) and VSCode is sending a 1.
This snippet shows a partial representation of the part of the message:
```
{
   "jsonrpc":"2.0",
   "id":0,
   "method":"initialize",
   "params":{
      "processId":43554,
      "clientInfo":{
         "name":"Visual Studio Code",
         "version":"1.52.0"
      },
      "locale":"en-us",
      "capabilities":{
         ....
         "textDocument":{
            ...
            "rename":{
               "dynamicRegistration":true,
               "prepareSupport":true,
               "prepareSupportDefaultBehavior":1, <-- Problematic field
               "honorsChangeAnnotations":true
            },
            ....
```

On the extension the dependencies are:
```
	"dependencies": {
		"vscode-languageclient": "^7.0.0"
	},
	"devDependencies": {
		"@types/glob": "^7.1.3",
		"@types/mocha": "^8.0.0",
		"@types/node": "^14.0.27",
		"@types/vscode": "^1.52.0",
		"@types/wait-on": "^5.2.0",
		"@typescript-eslint/eslint-plugin": "^4.1.1",
		"@typescript-eslint/parser": "^4.1.1",
		"eslint": "^7.9.0",
		"glob": "^7.1.6",
		"mocha": "^8.1.3",
		"net": "^1.0.2",
		"typescript": "^4.1.2"
	}
```

**Comment by pablocabrera85** [comment] 2020-12-17 12:37
Downgrading to 0.9.0 for now allowed me to continue working.

**Comment by cdietrich** [comment] 2020-12-17 13:22
this one was recently changed.

https://github.com/microsoft/language-server-protocol/commit/ed36538a180f15d33ffb03365fba4ace47b42d68

as the protocol 3.16 is now final i guess we need a final round for changes too

**Comment by pablocabrera85** [comment] 2020-12-17 14:07
Hi, thanks a lot for the reply. I'm glad to see it has already been taken care of. 

Do you know when a new version with the fix will be released?

**Comment by KamasamaK** [comment] 2020-12-17 16:33
If there's no more feedback on #472 within the next few days, I will merge the PR. There are a couple of other changes needed too for the final LSP 3.16 that I will submit after that.

I'm not sure for when the next release is scheduled.

**Comment by JulienBurnet86** [comment] 2021-01-04 08:12
Hello @KamasamaK,
I've seen you've merged #472 , does it include this issue ?
Thank you (and happy new year)

**Comment by KamasamaK** [comment] 2021-01-04 08:51
@JulienBurnet86 Yes, `prepareSupportDefaultBehavior` is now of type `org.eclipse.lsp4j.PrepareSupportDefaultBehavior` instead of `Boolean`.

https://github.com/eclipse/lsp4j/blob/af368bdeb4450613a8676cc21757dcc31bba53ea/org.eclipse.lsp4j/src/main/xtend-gen/org/eclipse/lsp4j/RenameCapabilities.java#L39

**Comment by nixel2007** [comment] 2021-01-04 11:23
@JulienBurnet86 you can get updated dependency from jitpack, if you need it asap.
Add jitpack as maven repo (here: https://github.com/1c-syntax/bsl-language-server/blob/feature/lsp4j-0.11.0/build.gradle.kts#L26) and replace lsp4j dependency (here https://github.com/1c-syntax/bsl-language-server/blob/feature/lsp4j-0.11.0/build.gradle.kts#L60)

**Comment by JulienBurnet86** [comment] 2021-01-04 13:22
@KamasamaK , @nixel2007 thanks !
I built the jar on my own from master, and will use it until the next release.
@KamasamaK : it has indeed fixed my issue !

**Comment by jonahgraham** [comment] 2021-01-04 13:34
> I'm not sure for when the next release is scheduled.

Nothing scheduled AFAIK. However we should release soon if 3.16 stuff is done. Please comment in #466 when the code is ready to be released and I will hit the buttons to do it.

**Comment by fwcd** [comment] 2021-03-05 01:22
I'm getting this issue with the currently released `0.10.0` version too:

```
java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 3207 path $.params.capabilities.textDocument.rename.prepareSupportDefaultBehavior
```

Using the current `master` seems to solve the problem though.

**Comment by jonahgraham** [comment] 2021-03-05 02:09
@fwcd Thanks for reporting that current master is working for you!


@KamasamaK does this ⬇⬇ comment mean the issue is fixed and can be closed?

> @JulienBurnet86 Yes, `prepareSupportDefaultBehavior` is now of type `org.eclipse.lsp4j.PrepareSupportDefaultBehavior` instead of `Boolean`.
> 
> https://github.com/eclipse/lsp4j/blob/af368bdeb4450613a8676cc21757dcc31bba53ea/org.eclipse.lsp4j/src/main/xtend-gen/org/eclipse/lsp4j/RenameCapabilities.java#L39

**Comment by KamasamaK** [comment] 2021-03-05 06:15
@jonahgraham Yes, the issue is fixed in the current snapshot. This was due to implementing unfinalized parts of the spec. I'm not sure if there's a good way to fail more gracefully when this happens. It's marked as `@Beta`, but that doesn't stop exceptions likes this, and I'd like to avoid things like this while still allowing us to keep up with unfinalized parts of the spec since sometimes LSP can take a long time between versions.

**Comment by jonahgraham** [comment] 2021-03-05 14:46
Thanks @KamasamaK - I am marking this issue as closed. If there is anything you would like to do as follow up it, please open a new issue.

**Closed by jonahgraham** 2021-03-05 14:46 UTC
Labels: bug
