### ISSUE TITLE
Exception on "initialized" method when parameter omitted

### ISSUE THREAD

**Issue by juergenhoetzel** [eclipse/lsp4j#94] opened 2017-05-09 10:37 UTC
According to http://www.jsonrpc.org/specification#request_object:

* params

> A Structured value that holds the parameter values to be used during the invocation of the method. This member MAY be omitted.

this is valid JSON-RPC:

```json
 {
  "jsonrpc": "2.0",
  "method": "initialized"
}
```
But results in:

```
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:49)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:108)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:165)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:136)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Related:

[Emacs/lsp-java: eclipse/lsp4j throws Exception on "initialized" method](https://github.com/emacs-lsp/lsp-java/issues/5)

**Comment by akosyakov** [comment] 2017-05-10 07:52
@juergenhoetzel Could you try with the latest changes, the stack trace does not match current sources and I cannot reproduce an issue.

**Comment by akosyakov** [comment] 2017-05-10 07:56
@juergenhoetzel I was able to reproduce with the old code, it is already fixed in the nightly snapshot

**Closed by akosyakov** 2017-05-10 07:56 UTC

**Comment by juergenhoetzel** [comment] 2017-05-10 09:11
> @juergenhoetzel I was able to reproduce with the old code, it is already fixed in the nightly snapshot

Had the same issue with latest snapshot: http://download.eclipse.org/jdtls/snapshots/jdt-language-server-0.1.0-201705081844.tar.gz

Replacing the bundled `org.eclipse.lsp4j.jsonrpc-0.2.0-SNAPSHOT.jar` file fixed the issue for me.

**Comment by akosyakov** [comment] 2017-05-10 09:36
@juergenhoetzel you should file a bug against jdt.ls then
