### ISSUE TITLE
Launcher.startListening() does not shut down when stream is closed, leaves process running

### ISSUE THREAD

**Issue by apatrida** [eclipse/lsp4j#358] opened 2019-08-20 16:19 UTC
The Launcher `startListening()` function indicates it shuts down its threads when the in/out streams close.  There is no other way to stop its thread pool from the outside.  

Yet, the launcher does not actually stop its thread pools, therefore the enclosing process does not shutdown.  Taking `DebugIntegrationTest.java` from the `org.eclipse.lsp4j.jsonrpc.debug` project and adding a `main()` to it clearly shows the problem:

```
    public static void main(String[] args) throws Exception {
	   System.out.println("before");
	   new DebugIntegrationTest().testBothDirectionRequests();
	   System.out.println("after");
	}
```

If you add stream closing to the test cas (see end), it still does not terminate.

```
@Test
	public void testBothDirectionRequests() throws Exception {
		// create client side
		PipedInputStream in = new PipedInputStream();
		PipedOutputStream out = new PipedOutputStream();
		PipedInputStream in2 = new PipedInputStream();
		PipedOutputStream out2 = new PipedOutputStream();

		in.connect(out2);
		out.connect(in2);

		MyClient client = new MyClient() {
			@Override
			public CompletableFuture<MyParam> askClient(MyParam param) {
				return CompletableFuture.completedFuture(param);
			}
		};
		Launcher<MyServer> clientSideLauncher = DebugLauncher.createLauncher(client, MyServer.class, in, out);

		// create server side
		MyServer server = new MyServer() {
			@Override
			public CompletableFuture<MyParam> askServer(MyParam param) {
				return CompletableFuture.completedFuture(param);
			}
		};
		Launcher<MyClient> serverSideLauncher = DebugLauncher.createLauncher(server, MyClient.class, in2, out2);

		clientSideLauncher.startListening();
		serverSideLauncher.startListening();

		CompletableFuture<MyParam> fooFuture = clientSideLauncher.getRemoteProxy().askServer(new MyParam("FOO"));
		CompletableFuture<MyParam> barFuture = serverSideLauncher.getRemoteProxy().askClient(new MyParam("BAR"));

		Assert.assertEquals("FOO", fooFuture.get(TIMEOUT, TimeUnit.MILLISECONDS).value);
		Assert.assertEquals("BAR", barFuture.get(TIMEOUT, TimeUnit.MILLISECONDS).value);

        // NEW! try to stop the thread pools by closing the streams:

		in.close();
		in2.close();
		out.close();
		out2.close();
	}
```

The unit tests only terminate because the unit test runner forces the process to stop when all tests complete.

Actually, about 90 seconds later this test `main()` does exit.  There should be a more controlled and definitive way to stop listening rather than only on the streams closing (and that should ALSO work).

A `stopListening()` or `shutdown()` method would be a nice option.

**Comment by spoenemann** [comment] 2019-08-21 14:07
LSP4J does react on closing the stream:

https://github.com/eclipse/lsp4j/blob/fb93ade4145a0df2a228f681dfbe46ae475c3a48/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/StreamMessageProducer.java#L79-L82

The problem is that the test does not specify any executor service, and so a cached thread pool is created, but never shut down. You can create the thread pool yourself, use it to create the launchers, and shut it down when the work is done, for example like this:

```java
public void testBothDirectionRequests() throws Exception {
	ExecutorService threadPool = Executors.newCachedThreadPool();
	
	// create client side
	PipedInputStream in = new PipedInputStream();
	PipedOutputStream out = new PipedOutputStream();
	PipedInputStream in2 = new PipedInputStream();
	PipedOutputStream out2 = new PipedOutputStream();

	in.connect(out2);
	out.connect(in2);

	MyClient client = new MyClient() {
		@Override
		public CompletableFuture<MyParam> askClient(MyParam param) {
			return CompletableFuture.completedFuture(param);
		}
	};
	Launcher<MyServer> clientSideLauncher = new Launcher.Builder<MyServer>()
			.setLocalService(client)
			.setRemoteInterface(MyServer.class)
			.setInput(in)
			.setOutput(out)
			.setExecutorService(threadPool)
			.create();

	// create server side
	MyServer server = new MyServer() {
		@Override
		public CompletableFuture<MyParam> askServer(MyParam param) {
			return CompletableFuture.completedFuture(param);
		}
	};
	Launcher<MyClient> serverSideLauncher = new Launcher.Builder<MyClient>()
			.setLocalService(server)
			.setRemoteInterface(MyClient.class)
			.setInput(in2)
			.setOutput(out2)
			.setExecutorService(threadPool)
			.create();

	clientSideLauncher.startListening();
	serverSideLauncher.startListening();

	CompletableFuture<MyParam> fooFuture = clientSideLauncher.getRemoteProxy().askServer(new MyParam("FOO"));
	CompletableFuture<MyParam> barFuture = serverSideLauncher.getRemoteProxy().askClient(new MyParam("BAR"));

	Assert.assertEquals("FOO", fooFuture.get(TIMEOUT, TimeUnit.MILLISECONDS).value);
	Assert.assertEquals("BAR", barFuture.get(TIMEOUT, TimeUnit.MILLISECONDS).value);

	out.close();
	out2.close();
	threadPool.shutdown();
}
```

**Comment by spoenemann** [comment] 2019-08-21 14:10
PS: Usually you would have to close the input stream, not the output stream, in order to stop the listening thread. But here we're using PipedInputStream, which requires the corresponding PipedOutputStream to be closed in order to return a `-1`.

**Comment by apatrida** [comment] 2019-08-22 12:20
@spoenemann thanks for the working approach.  Even when using input/output streams from processes it still does not shut down right away.  In the case of the Piped streams it takes 60-90 seconds to see the closed stream.

**Comment by apatrida** [comment] 2019-08-22 12:29
@spoenemann The ThreadPool `shutdown()` does not really happen right away either, there are still active threads for a while.  And if you want to wait until they are not active anymore, you have that long pause again for the close detection to actually happen.

So I want to shut down when every task is completed, but it shuts down much later.

```
   threadPool.awaitTermination(120, TimeUnit.SECONDS)
```

**Comment by apatrida** [comment] 2019-08-22 12:35
I can make it work with a final message from the server and tracking any pending requests on the sender, so it'll be fine as is.

**Comment by robstryker** [comment] 2020-07-14 18:58
Issue reporter says "it'll be fine as is" so I would argue this issue can be closed.

**Closed** 2020-07-15 06:12 UTC
