### ISSUE TITLE
Support CodeAction class

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#202] opened 2018-06-28 20:53 UTC
Protocol introduced a real CodeAction class which is much more convenient and rich: https://github.com/Microsoft/language-server-protocol/issues/389
LSP4J should add support for it too.

**Comment by mickaelistria** [comment] 2018-07-12 12:56
Seems like #204 should fix this.

**Comment by spoenemann** [comment] 2018-07-18 13:32
Duplicate of #194.

**Closed by spoenemann** 2018-07-18 13:32 UTC
