### ISSUE TITLE
Release v0.9.0

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#369] opened 2019-09-17 17:41 UTC
In LSP4E, we'd like to take advantage of some new features of LSP4J, for example to enable https://bugs.eclipse.org/bugs/show_bug.cgi?id=525411 . Could a release happen soon?

**Comment by mickaelistria** [comment] 2019-09-17 17:42
cc @PyvesB

**Comment by spoenemann** [comment] 2019-09-18 11:33
We could make 0.8.1 based on the current master state? Version 0.9.0 would require a release review and thus a delay of several weeks.

**Comment by cdietrich** [comment] 2019-09-18 11:34
@spoenemann release reviews are usually required once a year recently

**Comment by spoenemann** [comment] 2019-09-18 11:43
Is it documented somewhere? I haven't found anything in https://www.eclipse.org/projects/handbook/#release-review
CC @waynebeaton

**Comment by cdietrich** [comment] 2019-09-18 11:44
@spoenemann the same document states

> A Project can make official Releases for one calendar year following a successful Progress Review or Release Review. The Project Leadership Chain may—​at its discretion—​require that the Project engage in additional Reviews (e.g. a progress or Release Review) prior to issuing a Release.

**Comment by mickaelistria** [comment] 2019-09-18 12:30
Both a 0.8.1 or a 0.9.0 would be OK with me.
But @cdietrich is right, although the PMI doesn't make it clear, projects are now free to release minor versions just like the do for micro versions, without delay. A review (and related delay) is only required once a year now.

**Comment by waynebeaton** [comment] 2019-09-18 14:44
Making the PMI more helpful is on my list.

Service releases that are based on a previous major or minor release require no review (with no time restrictions). Service releases are releases that do not contain any new functionality (e.g., bug fixes only). What number you use is irrelevant: when a release includes new functionality, it is by definition either a major or minor release.

**Comment by spoenemann** [comment] 2019-09-25 08:19
@mickaelistria version 0.8.1 is on its way with the prepareRename fix. For 0.9.0 I'd like to also include at least #370.

**Comment by KamasamaK** [comment] 2019-09-25 09:01
Ideally, everything introduced in LSP 3.15 should make LSP4J 0.9.0. You can see a preview of the upcoming version at https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/.

**Comment by mickaelistria** [comment] 2019-09-25 09:32
> Ideally, everything introduced in LSP 3.15 should make LSP4J 0.9.0.

I guess it's up to those who need a feature or another to help make this happen.
So for example, the case of prepare rename support: @PyvesB wanted it in LSP4E and submitted the necessary change in LSP4J which got promptly reviewed and merged. IMO, it's the perfect workflow for LSP4J to keep evolving, rather than expecting people to implement support for operations they don't need (which is realistically not likely to happen).
So LSP4J may only include subset of the LSP spec, but it's a subset that's known to be used and tested (while developing some operations before a client or a server needs them can be perceived as a debt) and a subset whose development effort has been shared by more stakeholders. Far and efficient.

**Comment by KamasamaK** [comment] 2019-09-25 15:36
@mickaelistria Thanks for your input. I guess I misunderstood the goal of this project. If the project's prerogative is to only add features that are known to be used, then advertising the mapping of LSP4J versions to LSP versions in the README seems less useful since it's possible a feature could remain unimplemented due to this and that mapping would stagnate. As you say, "LSP4J may only include [a] subset of the LSP spec". I suppose something like a feature table would align better with the project goals, but maybe it's premature to assume that's needed at this point.

**Comment by spoenemann** [comment] 2019-09-26 07:27
Eventually we should have all of LSP 3.15.0 in LSP4J, but _when_ that goal is reached depends on the contributions, which in turn depend on the actual need for the new features. PRs are welcome.

**Comment by spoenemann** [comment] 2019-09-26 07:46
The Maven artifacts are published. But since direct SSH access to the Eclipse build servers was disabled, we cannot publish the P2 update site with the process we have used in the past. Unfortunately, I don't have time to work on a new publishing process now. Contributions are welcome.

See also #290.

**Comment by mickaelistria** [comment] 2019-09-26 12:02
Can you please mark the job (and the intermediary repo) as "Keep forever" so we can safely reference it downstream?

**Comment by mickaelistria** [comment] 2019-09-26 12:05
I can also try to help with the publish script, but I don't get where `:publishEclipseLsp4j` is defined, I couldn't find any occurrence of that term in the repo.

**Comment by cdietrich** [comment] 2019-09-26 12:06
@spoenemann you may c&p from here
https://github.com/eclipse/xtext-umbrella/blob/f63cebef19705e0da725fc87fb56e602edbbe90f/releng/jenkins/sign-and-deploy/Jenkinsfile#L144

**Comment by cdietrich** [comment] 2019-09-26 12:06
@mickaelistria you find the publish code here
https://github.com/typefox/publishing

**Comment by mundacho** [comment] 2019-10-01 10:04
Hello, I'll be happy to help with the build scripts, however, as I understand it, a new process needs to be defined to publish. Two questions come to mind:
- where can I find what the new process needs to do? is this https://github.com/typefox/publishing ?
- assuming I manage to do it, how can I test it?

**Comment by mundacho** [comment] 2019-10-01 19:55
Ok, this is what I found:
- lsp4j launches https://github.com/typefox/publishing to build and release
- the goal publishEclipseLsp4j (called from the Jenkins) just prepares the repository for lsp4j BUT it does not publish to the repository
- the code mentioned by @cdietrich effectively deploys to the eclipse project storage
- The Jenkins job for lsp4j-release just launches the gradle file (in the publishing project)

So... my guess is that to fix the release someone needs to configure the Jenkins to call the code mentioned by @cdietrich . I don't have access to configure that.
A more elegant solution is to have an extra subproject (releng) that uses a Jenkinsfile which we can create by getting inspiration from https://github.com/eclipse/xtext-umbrella/blob/f63cebef19705e0da725fc87fb56e602edbbe90f/releng/jenkins/sign-and-deploy/Jenkinsfile#L144 . Then, we just need to configure Jenkins to take that Jenkinsfile instead...

I don't have Jenkins access (to configure I mean), so I'm not sure how can I help with that. Please let me know, if there is a possibility to help.

**Comment by PyvesB** [comment] 2019-10-12 18:16
I believe the [Buildship](https://github.com/eclipse/buildship) team faced similar problems recently, they may be able to help.

**Comment by spoenemann** [comment] 2019-10-14 08:48
@mundacho thanks for the analysis so far! I can have a look at that when I find some time, but certainly not this week. Regarding the [Jenkins instance managed by Eclipse](https://ci.eclipse.org/lsp4j/), every [committer of LSP4J](https://projects.eclipse.org/projects/technology.lsp4j/who) should have access.

**Comment by cdietrich** [comment] 2019-11-15 14:36
@spoenemann any news on this issue

**Comment by mickaelistria** [comment] 2019-11-21 15:41
Is there any change this can happen early enough before SimRel so we can start building on top of it or is it recommended that we stay on 0.8.0?

**Comment by mickaelistria** [comment] 2019-11-25 16:45
Is the issue likely to be fixed for next SimRel with 0.9.0? We have some content pending in LSP4E that requires LSP4J 0.9.0, but I don't feel confident in switching to newer builds/snapshots as minimal version as long as LSP4J cannot be released... Please give reassuring news here ;)

**Comment by cdietrich** [comment] 2019-11-25 16:47
No if nobody fixes the deployment / replacement for shell access this will never be fixed

**Comment by jonahgraham** [comment] 2019-11-25 20:07
I am doing this now - focusing on the needs of simrel downstream projects requirements (e.g. lsp4e and cdt). A lot of the releng of lsp4j is inaccessible/uneditable to current committers, so the work I am doing is bringing this into Eclipse infra/git repos.

**Comment by jonahgraham** [comment] 2019-11-25 20:11
(updated title) - Note I am working on releasing 0.9.0 (current master HEAD), 0.8.1 probably won't ever be released to download.eclipse.org.

**Comment by jonahgraham** [comment] 2019-11-25 20:12
@spoenemann I am going to make a release record for 0.9.0 - unless you have an objection or want to do it yourself.

**Comment by cdietrich** [comment] 2019-11-25 20:12
Hmmm would be tight after m3 for downstream projects do adapt (don’t know how many breaking changes )

**Comment by jonahgraham** [comment] 2019-11-25 20:13
I am trying to get it in for M3 because downstream projects are asking for it.

**Comment by jonahgraham** [comment] 2019-11-26 14:51
I sent a message to cross-project-issues-dev.

**Comment by jonahgraham** [comment] 2019-11-26 17:59
I have created PR #378 that does building, signing and deploying on Eclipse infra and created new [multi-branch job](https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/) - each build automatically deploys to https://download.eclipse.org/lsp4j/builds/ in their own branch name's directory and uploads to maven central*. In addition I created a new [lsp4j-release-eclipse](https://ci.eclipse.org/lsp4j/job/lsp4j-release-eclipse/) job that handles copying a build to the [milestones](https://download.eclipse.org/lsp4j/updates/milestones/) or [releases](https://download.eclipse.org/lsp4j/updates/releases/) on download.eclipse.org.

 \* @spoenemann The deployment to maven central for snapshots is disabled because someone else is doing a daily deployment. Do you know whoe or where that is happening and can it be turned off please?

**Comment by jonahgraham** [comment] 2019-11-26 19:35
@cdietrich do you need the 0.9.0 released ahead of time - or does that wait until Eclipse simrel release day on 18 Dec.

**Comment by cdietrich** [comment] 2019-11-26 19:38
well the problem is that RC1 is next week and there should not really be changes beyond that.
so we would need that basically this week.

18th of december would be way to late for us (and for others like lsp4e too)
ps. did not see an answer of @mickaelistria on your cross project dev issues message

**Comment by jonahgraham** [comment] 2019-11-26 19:42
I was referring to the final release - i.e. Maven version 0.9.0 as opposed to 0.9.0-SNAPSHOT. The Snapshot/milestones are being done today.

**Comment by cdietrich** [comment] 2019-11-26 19:44
the problem is we have this:

https://github.com/eclipse/xtext-lib/tree/cd_xtext_issue1244
https://github.com/eclipse/xtext-core/pull/1307

specially for the first one we need a maven release.
or we would have to keep using 0.8.0 in maven 
and change the ranges in eclipse to `[0.8.0,0.10.0)`

**Comment by cdietrich** [comment] 2019-11-26 19:45
see also https://wiki.eclipse.org/Category:SimRel-2019-12

**Comment by jonahgraham** [comment] 2019-11-26 19:51
OK, I understand - the difference is LSP4E and CDT which depend **only** on P2 versions, no reliance on Maven version. So this still isn't resolved yet as we need to be sure we can get the 0.9.0 version released to Maven today. All the infra is done with #378 for Maven snapshots and full P2 releases.

**Comment by cdietrich** [comment] 2019-11-26 19:52
not strictly today but somewhen this week e.g. on thursday would be nice

**Comment by jonahgraham** [comment] 2019-11-26 19:54
But I have to be confident today that we can do the release or I better not release 0.9.0 to SimRel :-)

**Comment by cdietrich** [comment] 2019-11-26 19:56
Sure. 2020-03 is coming fast anyway with holiday season eating some time

**Comment by cdietrich** [comment] 2019-11-26 20:25
@jonahgraham problem might be that https://github.com/eclipse/lsp4j/blob/129c970b981f5ce42a2bea75b2af0b2076c69f65/releng/deploy-build.sh#L37 uses snapshots always

**Comment by jonahgraham** [comment] 2019-11-26 20:29
Yes, you are correct - that is a mistake. 

A bigger issue is releasing the deployment from staging to maven central. i.e. it is no help if I deploy to staging if we can't get it to the next step :-)

**Comment by cdietrich** [comment] 2019-11-26 20:30
Do you have any idea who can do what
@svenefftinge @dhuebner it would really be nice if you could help out here

**Comment by jonahgraham** [comment] 2019-11-26 20:38
@cdietrich and @mickaelistria - you are the two that care about versions the most. There are some complications in getting 0.9.0 done, I thought we had a bit more time than we do. 

Instead of rushing on 0.9.0, AFAIU [0.8.1](https://search.maven.org/artifact/org.eclipse.lsp4j/org.eclipse.lsp4j/0.8.1/jar) has been released to Maven Central already and what is missing for LSP4E is having 0.8.1 in simrel. The 0.8.1 seems to have @PyvesB's [fix](https://github.com/eclipse/lsp4j/commit/7f143e0a02ec59682399d3501b3592eff4c387ab).

So, if there are no objections I will upload 0.8.1 to downloads.eclipse.org and update simrel for that. The p2 repo is already here: https://ci.eclipse.org/lsp4j/job/lsp4j-release/28/artifact/build-result/p2.repository/ - not sure why it wasn't deployed to downloads.eclipse.org?

In the background I will continue trying to get the builds fully automated on Eclipse infra so that we can release fully off eclipse infra.

**Comment by cdietrich** [comment] 2019-11-26 20:39
I Would be fine with that

**Comment by mickaelistria** [comment] 2019-11-26 20:47
I'd also be happy with a 0.8.1 that contains @PyvesB patch.

**Comment by jonahgraham** [comment] 2019-11-26 21:28
I have added v0.8.1 to SimRel: https://git.eclipse.org/r/#/c/153441/ - and provided a patch for LSP4E to use it too: https://git.eclipse.org/r/#/c/153442/

@cdietrich AFAICT with 2019-12 having 0.8.1 then you don't have to make any changes now. 

For v0.9.0 I have changed release date to sometime in time for 2020-03 - there are some big changes on DAP due but I didn't want to merge yet as not quite ready, e.g.  PR #376

**Comment by PyvesB** [comment] 2019-11-26 21:41
Thanks for taking care of this! Glad to see that my patch will probably make it in Eclipse 2019-12 (and hopefully be useful to other consumers of LSP4J too)!

**Comment by jonahgraham** [comment] 2019-11-26 22:01
@PyvesB thank you for your patience on this. I am very happy that we have a solution, hopefully we can get future patches turned around without so much last minute angst!

**Comment by jonahgraham** [comment] 2020-01-30 02:22
0.9.0 will be part of the 2020-03 SimRel - I will be making the contribution in time for M2 next week. I set the release date to 2 March (RC1 + 1 day), just ahead of the 2020-03 release on 18 March. This is because projects such as Xtext actually need LSP4J to be released to maven central before they can make their final contribution to 2020-03 SimRel (@cdietrich please confirm this date is OK for Xtext - or advise if I have misunderstood requirements). As we have had a review in August 2019, less than a year ago, we do not need a release review.

PMI entry: https://projects.eclipse.org/projects/technology.lsp4j/releases/0.9.0

We still have a few issues to resolve on finishing automated builds, especially getting things published consistently to maven central. I will highlight those issues and make sure their target milestone is properly updated too.

**Comment by cdietrich** [comment] 2020-01-30 05:05
Generally yes
But as there is no snapshot yet we cannot adapt This week
also about the timeline
We usually build the milestone on Monday / Tuesday and would need a consumable p2 and maven item then

As the dependency is optional it might be ok to consume the old 
081 for the m2 from our side

**Comment by jonahgraham** [comment] 2020-01-30 11:46
@cdietrich I'm aiming to have p2 and Maven snapshot for m2 today. I'll post here when I am done.

**Comment by cdietrich** [comment] 2020-01-30 11:48
nice. thankyou. i already a look at the code and the number of required changes (at least compile error wise) is not too big. basically signature help service.

have to think about how we deal with the deprecation of MarkedString though

**Comment by cdietrich** [comment] 2020-01-30 11:49
is there a reason the MarkedString thing in Hover is not transitively deprecated?

**Comment by jonahgraham** [comment] 2020-01-30 19:00
0.9.0 M2 published to https://download.eclipse.org/lsp4j/updates/milestones/S202001301830/

I will be adding that to simrel too, but because of the API change I am coordinating that with LSP4E and CDT at least it may not make it into simrel today.

**Comment by jonahgraham** [comment] 2020-01-30 19:15
The snapshot is in [maven](https://oss.sonatype.org/#nexus-search;gav~org.eclipse.lsp4j~org.eclipse.lsp4j~~~~kw,versionexpand) too now - but see #402 as I am concerned that someone else is publishing older content in the same namespace. I'll keep an eye on it and if it gets overridden I will publish a newer snapshot again (by running build of master branch).

**Comment by cdietrich** [comment] 2020-01-30 19:18
is it possible the problem is the repo list here
pointing to old places: https://github.com/TypeFox/publishing/blob/master/build.gradle

**Comment by cdietrich** [comment] 2020-01-30 19:22
maybe you can fork that and add some prints so that we see what it actually does

**Comment by jonahgraham** [comment] 2020-01-30 19:26
Thanks @cdietrich  - you are correct, that script keeps republishing http://services.typefox.io/open-source/jenkins/job/lsp4j/job/master/lastSuccessfulBuild/ - and as services.typefox.io is not working anymore for lsp4j that is the problem.

**Comment by jonahgraham** [comment] 2020-01-30 19:29
But that leaves the question I don't get - who is running that build.gradle still? I don't think it is anything on https://ci.eclipse.org/lsp4j.

**Comment by cdietrich** [comment] 2020-01-30 19:44
see my comments in https://github.com/eclipse/lsp4j/issues/402

**Comment by jonahgraham** [comment] 2020-02-01 00:07
> I will be adding that to simrel too, but because of the API change I am coordinating that with LSP4E and CDT at least it may not make it into simrel today.

Done: https://git.eclipse.org/r/#/c/156990/

**Comment by cdietrich** [comment] 2020-02-03 08:42
@jonahgraham changing the Xtext code so far worked fine. i saw that the milestone is planned to be published as maven only and not to maven central as it was in the past.
this gives us the problem that we have to publish/test our milestones with a snapshot dependency.
it also strikes me if you releasing on march 2. ottawa time and us on march 3rd european time if this is way to close. in the past the publishing of both was done by typefox so that such a short notice was no problem but now we have to sync.

=> is it possible to have milestones published again
=> can you tell about the exact planned release date/time.

**Comment by jonahgraham** [comment] 2020-02-03 11:53
@cdietrich sure thing, all that is possible, thank you for letting me know what is needed. I'm not sure if I will be able to get an M2 milestone published to central in time for xtext. If I don't, I'll publish an M3 very early to make sure that the flow works as I don't have a successful publish done yet, see #403

I have no attachment to release dates, so please make a proposal.

**Comment by cdietrich** [comment] 2020-02-03 12:00
we are fine with m3. 
the eclipse dependency is optional anyway and i assume nobody uses it.
(or can test using snapshots)

having a m3 would be nice.
for the release it would be nice to have it on the thursday/friday timeframe (27/28) as typefox did it in the past

**Comment by jonahgraham** [comment] 2020-02-03 12:09
👍 M3 will be published to simrel and Maven central on 20 Feb and release on 27 Feb, both Ottawa time.

**Comment by jonahgraham** [comment] 2020-02-03 12:21
https://projects.eclipse.org/projects/technology.lsp4j/releases/0.9.0 and https://github.com/eclipse/lsp4j/milestone/15 updated to new dates.

**Comment by cdietrich** [comment] 2020-02-03 12:26
thanks

**Comment by jonahgraham** [comment] 2020-02-21 04:03
I have published what will probably be M3. I will contribute to SimRel hopefully tomorrow or day after as I may have some API cleanups to do in LSP4E, especially related to PR #412 

See comment https://github.com/eclipse/lsp4j/issues/403#issuecomment-589487317 about Maven Central and the workaround.

**Comment by jonahgraham** [comment] 2020-02-21 04:07
PS The milestone release p2 URL is https://download.eclipse.org/lsp4j/updates/milestones/S202002202238

**Comment by jonahgraham** [comment] 2020-02-25 04:43
M3 contributed to simrel: https://git.eclipse.org/r/#/c/158272/

**Comment by jonahgraham** [comment] 2020-02-28 03:00
#415 is resolved - but #413 should be resolved before release too and I can't finish that today - I will aim to do that tomorrow. @cdietrich I think you are the most affected by a delay with xtext - sorry about that.

**Comment by jonahgraham** [comment] 2020-02-29 17:00
[0.9.0](https://github.com/eclipse/lsp4j/releases/tag/v0.9.0) <-- see that URL for info.

The master branch has been updated to [0.10.0-SNAPSHOT](https://github.com/eclipse/lsp4j/commit/126a33e41b5451af64bbfe69d614ddcba7820ce5) and if we need it I can prepare a 0.9.1-SNAPSHOT branch. The [builds/master on downloads](https://download.eclipse.org/lsp4j/builds/master/) is now 0.10.0 and it is being published to sonatype [snapshots](https://oss.sonatype.org/service/local/repositories/snapshots/content/org/eclipse/lsp4j/org.eclipse.lsp4j/0.10.0-SNAPSHOT/) too.

**Closed by jonahgraham** 2020-02-29 17:00 UTC

**Comment by cdietrich** [comment] 2020-02-29 17:16
integrated the release in Xtext maven/gradle and p2 and it works nicely. thanks @jonahgraham
