### ISSUE TITLE
Upload to sonatype snapshots broken?

### ISSUE THREAD

**Issue by cdietrich** [eclipse/lsp4j#610] opened 2022-04-29 06:16 UTC
```
mvn dependency:get -U -DgroupId=org.eclipse.lsp4j -DartifactId=org.eclipse.lsp4j -Dversion=0.13.0-SNAPSHOT  -DrepoUrl=https://oss.sonatype.org/content/repositories/snapshots
```
does  seem to work.
but consuming it from gradle does not

https://github.com/cdietrich/lsp4j_issue610

```
./gradlew clean build --gradle-user-home=.gx --refresh-dependencies
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.eclipse.lsp4j:org.eclipse.lsp4j:0.13.0-SNAPSHOT.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/0.13.0-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/0.13.0-SNAPSHOT/org.eclipse.lsp4j-0.13.0-20220429.053938-94.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
am not sure how often sonatype updates metadata

```
curl https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/0.13.0-SNAPSHOT/maven-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata modelVersion="1.1.0">
  <groupId>org.eclipse.lsp4j</groupId>
  <artifactId>org.eclipse.lsp4j</artifactId>
  <versioning>
    <lastUpdated>20220429053938</lastUpdated>
    <snapshot>
      <timestamp>20220429.053938</timestamp>
      <buildNumber>94</buildNumber>
    </snapshot>
    <snapshotVersions>
      <snapshotVersion>
        <classifier>javadoc</classifier>
        <extension>jar</extension>
        <value>0.13.0-20220429.053938-94</value>
        <updated>20220429053938</updated>
      </snapshotVersion>
      <snapshotVersion>
        <classifier>sources</classifier>
        <extension>jar</extension>
        <value>0.13.0-20220429.053938-93</value>
        <updated>20220429053938</updated>
      </snapshotVersion>
      <snapshotVersion>
        <extension>jar</extension>
        <value>0.13.0-20220429.053938-92</value>
        <updated>20220429053938</updated>
      </snapshotVersion>
      <snapshotVersion>
        <extension>pom</extension>
        <value>0.13.0-20220429.053938-92</value>
        <updated>20220429053938</updated>
      </snapshotVersion>
    </snapshotVersions>
  </versioning>
  <version>0.13.0-SNAPSHOT</version>
</metadata>
```

**Comment by cdietrich** [comment] 2022-04-29 06:29
<img width="849" alt="Bildschirmfoto 2022-04-29 um 08 28 59" src="https://user-images.githubusercontent.com/238736/165894874-be9e4ced-4a9b-4a7d-bc95-47568a10753d.png">

**Comment by cdietrich** [comment] 2022-04-29 06:35
created https://github.com/gradle/gradle/issues/20605

**Comment by cdietrich** [comment] 2022-05-02 04:43
gradle team also said there might be something wrong on our side and we should use consistent build number

**Comment by cdietrich** [comment] 2022-05-02 05:20
the funny thing is we even seem to do the upload in one pass, with 1 buildnumber

07:39:37  + mvn gpg:sign-and-deploy-file -DpomFile=build/maven-repository/org/eclipse/lsp4j/org.eclipse.lsp4j/0.13.0-SNAPSHOT/org.eclipse.lsp4j-0.13.0-20220429.053854-1.pom -Dfile=build/maven-repository/org/eclipse/lsp4j/org.eclipse.lsp4j/0.13.0-SNAPSHOT/org.eclipse.lsp4j-0.13.0-20220429.053854-1.jar -Dsources=build/maven-repository/org/eclipse/lsp4j/org.eclipse.lsp4j/0.13.0-SNAPSHOT/org.eclipse.lsp4j-0.13.0-20220429.053854-1-sources.jar -Djavadoc=build/maven-repository/org/eclipse/lsp4j/org.eclipse.lsp4j/0.13.0-SNAPSHOT/org.eclipse.lsp4j-0.13.0-20220429.053854-1-javadoc.jar -Durl=https://oss.sonatype.org/content/repositories/snapshots/ -DrepositoryId=ossrh

but wee dont seem to use -SNAPSHOT as name

**Comment by cdietrich** [comment] 2022-05-02 05:36
@jonahgraham  can we run the sign-and-deploy with -X to maybe get some additional insights

**Comment by jonahgraham** [comment] 2022-05-02 14:27
Added -X in 8777dc3a082549da7942be5d21714c5cb4b900cd - https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/main/22/ is running now

**Comment by cdietrich** [comment] 2022-05-02 14:39
wonder
if
` <generatePom default-value="true">${generatePom}</generatePom>`
and 
`<session default-value="${session}"/>`
could be related

**Comment by cdietrich** [comment] 2022-05-02 14:54
nope seems both fine :(

**Comment by jonahgraham** [comment] 2022-05-02 15:01
The `-X` didn't add any useful information as far as I can see. I have no idea how to debug this problem as I can't run this part of the build locally. I am trying another build without sources/javadoc to see if that is consistent (although nexus may reject a build with no sources/javadoc, I can't remember)

**Comment by cdietrich** [comment] 2022-05-02 15:02
i wonder we could setup nexus locally and deploy to that local nexus.
but i have done that 10 years ago the last time

**Comment by jonahgraham** [comment] 2022-05-02 15:07
> @jonahgraham why cannot you build locally?

Because the issue is the deploy side which needs keys, etc that are stored on CI.

**Comment by jonahgraham** [comment] 2022-05-02 15:08
I am running another experiment - https://github.com/eclipse/lsp4j/tree/release_0.12.1 - to make a 0.12.1-SNAPSHOT to see if that does anything useful.

**Comment by cdietrich** [comment] 2022-05-02 15:09
we might be able to open a bug at sonatype, but i have doubts this would help.

**Comment by jonahgraham** [comment] 2022-05-02 15:10
With just the main jar/pom, I get past the error you reported, your example now gives me:

```
$ ./gradlew clean build --gradle-user-home=.gx --refresh-dependencies
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.eclipse.xtend:org.eclipse.xtend.lib:2.24.0.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xtend/org.eclipse.xtend.lib/2.24.0/org.eclipse.xtend.lib-2.24.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > org.eclipse.lsp4j:org.eclipse.lsp4j:0.13.0-SNAPSHOT:20220502.150614-101 > org.eclipse.lsp4j:org.eclipse.lsp4j.generator:0.13.0-SNAPSHOT:20220502.150634-101
   > Could not find any version that matches com.google.code.gson:gson:[2.8.9,2.9).
     Versions that do not match: 2.7-SNAPSHOT
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/google/code/gson/gson/maven-metadata.xml
     Required by:
         project : > org.eclipse.lsp4j:org.eclipse.lsp4j:0.13.0-SNAPSHOT:20220502.150614-101 > org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.13.0-SNAPSHOT:20220502.150643-101
```

**Comment by jonahgraham** [comment] 2022-05-02 15:10
In https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/0.13.0-SNAPSHOT/maven-metadata.xml the buildNumber matches the version of jar/pom.

**Comment by cdietrich** [comment] 2022-05-02 15:11
yes you need to add mavenCentral() to repo list

**Comment by cdietrich** [comment] 2022-05-02 15:12
<img width="716" alt="Bildschirmfoto 2022-05-02 um 17 11 48" src="https://user-images.githubusercontent.com/238736/166258771-32d7b278-1e94-4b2d-aec9-5efb676ee562.png">

**Comment by cdietrich** [comment] 2022-05-02 15:14
works for me now. i wonder if the order of the files deployed in random and if the jar is last, it wll be there?

**Comment by jonahgraham** [comment] 2022-05-02 15:20
When I revert 2ba39d32ff7a26d4ee580ed8c0439c93626a00a7 I expect the problem to reoccur.

**Comment by cdietrich** [comment] 2022-05-02 15:23
this reminds me that i somewhere read
people use 
-file=the jar
-files=thejavadoc,thesources
-classifiers

to solve the buildnumber problem, will try to find it again

**Comment by jonahgraham** [comment] 2022-05-02 15:26
Thanks @cdietrich - I will try that too.

**Comment by jonahgraham** [comment] 2022-05-02 15:39
My commit message prematurely closed this issue. https://github.com/eclipse/lsp4j/issues/610#issuecomment-1115030941 (in commit ece9e5e76437e4ed32f96d574679df6993b4eb7c) did not resolve the issue.

My 0.12.1 branch has the same issue (I was hoping that maybe starting a new directory on sonatype would be a solution).

@cdietrich - other than reapplying 2ba39d32ff7a26d4ee580ed8c0439c93626a00a7 I don't know what else to do on this one.

**Comment by cdietrich** [comment] 2022-05-02 15:43
Can you also try the older plugin version mentioned in the blog

**Comment by jonahgraham** [comment] 2022-05-02 15:51
I am trying older version - as it turns out when LSP4J 0.12.0  was released the version of the gpg plugin was a much older one and the command line we are using just uses latest. See released versions: https://search.maven.org/artifact/org.apache.maven.plugins/maven-gpg-plugin

**Comment by jonahgraham** [comment] 2022-05-02 15:52
See 045557687d81c6c36057aa5d6a2e86fb0d717ab2 (which said #601 by mistake)

**Comment by jonahgraham** [comment] 2022-05-02 16:06
Yup - the older version fixed the problem AFAICT:

[maven-metadata.xml](https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/0.13.0-SNAPSHOT/maven-metadata.xml):

```xml

<?xml version="1.0" encoding="UTF-8"?>
<metadata modelVersion="1.1.0">
  <groupId>org.eclipse.lsp4j</groupId>
  <artifactId>org.eclipse.lsp4j</artifactId>
  <versioning>
    <lastUpdated>20220502160227</lastUpdated>
    <snapshot>
      <timestamp>20220502.160227</timestamp>
      <buildNumber>105</buildNumber>
    </snapshot>
    <snapshotVersions>
      <snapshotVersion>
        <extension>jar</extension>
        <value>0.13.0-20220502.160227-105</value>
        <updated>20220502160227</updated>
      </snapshotVersion>
      <snapshotVersion>
        <extension>pom</extension>
        <value>0.13.0-20220502.160227-105</value>
        <updated>20220502160227</updated>
      </snapshotVersion>
      <snapshotVersion>
        <classifier>javadoc</classifier>
        <extension>jar</extension>
        <value>0.13.0-20220502.160227-105</value>
        <updated>20220502160227</updated>
      </snapshotVersion>
      <snapshotVersion>
        <classifier>sources</classifier>
        <extension>jar</extension>
        <value>0.13.0-20220502.160227-105</value>
        <updated>20220502160227</updated>
      </snapshotVersion>
    </snapshotVersions>
  </versioning>
  <version>0.13.0-SNAPSHOT</version>
</metadata>


```

I'll file a bug.

**Comment by jonahgraham** [comment] 2022-05-02 16:13
Jira: https://issues.apache.org/jira/browse/MGPG-85

**Closed by jonahgraham** 2022-05-02 16:13 UTC

**Comment by cdietrich** [comment] 2022-05-02 17:26
thx @jonahgraham
